### ISSUE TITLE
Projekt választás

### ISSUE THREAD

**Issue by tm4s** [kissdani06/temalabor#2]
Az alábbi projektek közül kellene egyet-egyet választani:

C# 
https://github.com/App-vNext/Polly
https://github.com/aalhour/C-Sharp-Algorithms
https://github.com/github/Scientist.net

Java 
https://github.com/pedrovgs/Algorithms
https://github.com/yangfuhai/ASimpleCache
https://github.com/stleary/JSON-java

**Comment by reischlb** [comment]
c#: algo
java: algo
